FROM python:alpine
MAINTAINER Kevin Hernandez <kevteg05@gmail.com>
ENV PYTHONUNBUFFERED 1

RUN mkdir /code
WORKDIR /code

RUN apk --update add --virtual build-dependencies build-base git openssl-dev  libc-dev linux-headers
ADD requirements.txt /code/requirements.txt
RUN pip install -r requirements.txt
ADD . /code
